InternTimeStamp/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;

namespace InternTimeStamp.Controllers
{
    public class CalendarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InternTimeStamp/Controllers/InternStudentsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using Dapper;
using InternTimeStamp.Models;

namespace InternTimeStamp.Controllers
{
    public class InternStudentsController : Controller
    {
        SqlDataReader dr;

        private readonly IConfiguration configuration;

        public InternStudentsController(IConfiguration config)
        {
            this.configuration = config;
        }

        public IActionResult Index()
        {
            var viewModel = new ViewModels.InternStudentList.IndexViewModels();
            viewModel.InternStudentLists = new List<InternStudent>();
            viewModel.UniversityLists = new List<University>();
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            // query intern
            connection.Open();
            //connection.Query<InternStudent>("SELECT TOP (1000) [Name] ,[University_code] FROM [Intern] ORDER BY [LastModifyDate] ASC").ToList();

            SqlCommand queryInternCmd = new SqlCommand("SELECT [Name], [University_code] FROM [Intern] ORDER BY [LastModifyDate] ASC", connection);
            dr = queryInternCmd.ExecuteReader();
            while (dr.Read())
            {
                viewModel.InternStudentLists.Add(new InternStudent() { Name = dr.GetString(0), University = dr.GetString(1) });
            }
            connection.Close();

            // query university
            connection.Open();
            //connection.Query<University>("SELECT TOP(1000)[Code],[University] FROM[University] ORDER BY[LastModifyDate] ASC").ToList();

            SqlCommand queryUnivCmd = new SqlCommand("SELECT [UniversityName] FROM [University] ORDER BY [LastModifyDate] ASC", connection);
            dr = queryUnivCmd.ExecuteReader();

            while (dr.Read())
            {
                viewModel.UniversityLists.Add(new University() { UniversityName = dr.GetString(0) });
            }
            connection.Close();

            return View(viewModel);
        }

        // add
        [HttpPost]
        public ActionResult Index(InternStudent intern_student)
        {
            var listInternStudent = new List<InternStudent>();
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            connection.Execute("INSERT INTO [Intern] ([Name], [University_code], [LastModifyDate]) VALUES (@Name, @University_code, getdate())",
                new
                {
                    Name = intern_student.Name,
                    University_code = intern_student.University,
                    LastModifyDate = intern_student.LastModifyDate.AddHours(+7)
                });

            //SqlCommand insertCmd = new SqlCommand("INSERT INTO Intern(Name, University_Code, LastModifyDate) VALUES(@Name, @University_Code, getdate())");
            //insertCmd.Connection = connection;
            //insertCmd.Parameters.AddWithValue("@Name", intern_list.Name);
            //insertCmd.Parameters.AddWithValue("@University_Code", intern_list.University_Code);
            //insertCmd.ExecuteNonQuery();

            listInternStudent = connection.Query<InternStudent>("SELECT [Name],[University_code] FROM [Intern] ORDER BY [LastModifyDate] ASC").ToList();

            //SqlCommand queryCmd = new SqlCommand("SELECT TOP (1000) [Name],[University_Code] FROM [Intern] ORDER BY [LastModifyDate] ASC", connection);
            //dr = queryCmd.ExecuteReader();

            //while (dr.Read())
            //{
            //    listIntern.Add(new Intern() { Name = dr.GetString(0), University_Code = dr.GetString(1) });
            //}

            connection.Close();

            return View(listInternStudent);
        }


        // getid
        [HttpGet]
        [Route("InternStudents/Get/{name}")]
        public IActionResult GetByName(string name)
        {
            var result = new InternStudent();
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            SqlCommand queryCmd = new SqlCommand("select [Name] FROM [Intern] WHERE Name=@Name", connection);
            queryCmd.Connection = connection;
            queryCmd.Parameters.AddWithValue("@Name", name);
            dr = queryCmd.ExecuteReader();

            while (dr.Read())
            {
                result.Name = dr.GetString(0);
            }

            connection.Close();

            return Ok(result);
        }


        // delete
        [HttpGet]
        [Route("InternStudents/Delete/{name}")]
        public IActionResult delete(string name)
        {
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            connection.Execute("DELETE FROM [Intern] WHERE Name=@Name",
                new
                {
                    name = name
                });

            connection.Close();
            return Ok("successfully deleted!");
        }

        // edit
        [HttpPost]
        [Route("InternStudents/Edit/{name}")]
        public ActionResult Edit(InternStudent intern_student)
        {
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            connection.Execute("UPDATE [Intern] SET[Name] = @Name,[University_code] = @University_code, [LastModifyDate] = getdate() WHERE Name=@Name",
                new
                {
                    Name = intern_student.Name,
                    University_Code = intern_student.University,
                    LastModifyDate = intern_student.LastModifyDate
                });

            //SqlCommand editCommand = new SqlCommand("UPDATE [Intern] SET[Name] = @Name,[University_code] = @University_code, [LastModifyDate] = getdate() WHERE Name=@Name", connection);
            //editCommand.Parameters.AddWithValue("@Name", university.Code);
            //editCommand.Parameters.AddWithValue("@University_code", university.Universities);
            //editCommand.ExecuteNonQuery();

            connection.Query<InternStudent>("SELECT [Name],[University_แode] FROM [Intern] ORDER BY [LastModifyDate] ASC").ToList();

            //SqlCommand queryCmd = new SqlCommand("SELECT TOP (1000) [Name],[University_Code] FROM [Intern] ORDER BY [LastModifyDate] ASC", connection);
            //dr = queryCmd.ExecuteReader();

            //while (dr.Read())
            //{
            //    listUniversity.Add(new University() { Code = dr.GetString(0), Universities = dr.GetString(1) });
            //}

            connection.Close();

            return Ok("Successfully Edited!");
        }

    }
}

InternTimeStamp/Controllers/UniversitiesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using InternTimeStamp.Models;
using Dapper;

namespace InternTimeStamp.Controllers
{
    public class UniversitiesController : Controller
    {
        SqlDataReader dr;
        private readonly IConfiguration configuration;
        public UniversitiesController(IConfiguration config)
        {
            this.configuration = config;
        }
        List<University> universities = new List<University>();


        // index
        public IActionResult Index()
        {
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            universities = connection.Query<University>("SELECT [Code],[UniversityName] FROM [University] ORDER BY [LastModifyDate] ASC").ToList();

            connection.Close();

            return View(universities);
        }


        // add
        [HttpPost]
        public ActionResult Index(University university)
        {
            List<University>? listUniversity = new List<University>();
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);
            bool bIfExist = false;

            connection.Open();

            connection.Execute("INSERT INTO University([Code], [UniversityName], [LastModifyDate]) VALUES(@Code, @UniversityName, getdate())",
                new
                {
                    Code = university.Code,
                    UniversityName = university.UniversityName,
                    LastModifyDate = university.LastModifyDate.AddHours(+7)
                });

            listUniversity = connection.Query<University>("SELECT [Code],[UniversityName] FROM [University] ORDER BY [LastModifyDate] ASC").ToList();

            connection.Close();

            return View(listUniversity);
        }


        // edit
        [HttpPost]
        [Route("Universites/Edit/{code}")]
        public ActionResult Edit(University university)
        {
            var listUniversity = new List<University>();
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();

            connection.Execute("UPDATE [University] SET [Code] = @Code ,[UniversityName] = @UniversityName ,[LastModifyDate] = getdate() WHERE Code=@Code",
                new
                {
                    Code = university.Code,
                    UniversityName = university.UniversityName,
                    LastModifyDate = university.LastModifyDate.AddHours(+7)
                });

            connection.Query<University>("SELECT [Code],[UniversityName] FROM [University] ORDER BY [LastModifyDate] ASC").ToList();

            connection.Close();

            return Ok("Successfully Edited!");
        }


        // getid
        [HttpGet]
        [Route("Universities/Get/{code}")]
        public IActionResult GetByCode(string code)
        {
            var result = new University();
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            SqlCommand queryCmd = new SqlCommand("select [Code], [UniversityName] FROM [University] WHERE Code=@Code", connection);
            queryCmd.Connection = connection;
            queryCmd.Parameters.AddWithValue("@Code", code);
            dr = queryCmd.ExecuteReader();

            while (dr.Read())
            {
                result.Code = dr.GetString(0);
                result.UniversityName = dr.GetString(1);
            }

            connection.Close();

            return Ok(result);
        }


        // delete
        [HttpGet]
        [Route("Universities/Delete/{code}")]
        public IActionResult Delete(string code)
        {
            string connectionstring = configuration.GetConnectionString("defaultConnectionString");
            SqlConnection connection = new SqlConnection(connectionstring);

            connection.Open();
            connection.Execute("DELETE FROM [University] WHERE Code=@Code",
                new
                {
                    Code = code
                });

            connection.Close();

            return Ok("Successfully Deleted!");
        }

    }
}

InternTimeStamp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternTimeStamp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternTimeStamp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InternTimeStamp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timestamps"
                               asp-action="Index">Timestamps</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar"
                               asp-action="Index">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InternStudents" asp-action="Index">
                                Internship Students
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Universities"
                               asp-action="Index">Universities</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2565 - InternTimeStamp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>